"""GN solver roundtrip unit test (decoupled from network).

For each DoF preset × projection model:
  (A) Pose roundtrip: random δ_gt → project → solve_*() → does δ_est match
      δ_gt? How many iterations to hit machine precision (float64)?
  (B) Covariance roundtrip: given clean Σ_obs (per-pixel observation cov),
      does H⁻¹ from H = Σ_i Jᵢᵀ Wᵢ Jᵢ match the empirical Cov(δ̂ - δ_gt) of a
      Monte-Carlo run? — i.e. is H the correct Cramér-Rao bound?

Geometry-only: no CalibNetDepth, no dataset. cam-frame XYZ generated by
random sampling; K and KB dist set to realistic camera values.

Run:
  PYENV_VERSION=3.10.4 python scripts/_debug/test_gn_roundtrip.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import torch

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

from scripts.ba.ba_torch import (
    project_pinhole, project_kb,
    pinhole_jacobian, kb_jacobian,
    solve_pinhole, solve_kb,
    _apply_extrinsic, _K_with_delta,
)

torch.set_default_dtype(torch.float64)
DEVICE = 'cpu'   # float64 MC test, CPU is fine


# ─── shared helpers ───────────────────────────────────────────────────

def make_cam_xyz(n: int, *, z_lo=2.0, z_hi=80.0, fov_half=0.6, seed=0) -> torch.Tensor:
    """Sample cam-frame (X, Y, Z) in front of camera with Z bucketed
    (handful close, handful far) so depth is well-spread for tx/yaw split."""
    rng = np.random.RandomState(seed)
    z = np.exp(rng.uniform(np.log(z_lo), np.log(z_hi), n))
    # sample (x/z, y/z) inside ±tan(fov_half) ≈ ±0.6 → ≈ ±31°
    xz = rng.uniform(-fov_half, fov_half, n)
    yz = rng.uniform(-fov_half, fov_half, n)
    X = xz * z
    Y = yz * z
    Z = z
    return torch.tensor(np.stack([X, Y, Z], axis=-1), dtype=torch.float64)


def real_K(B=1) -> torch.Tensor:
    """A realistic-ish K (fx≈900, cx=cy=512)."""
    K = torch.zeros(B, 3, 3, dtype=torch.float64)
    K[:, 0, 0] = 900.0
    K[:, 1, 1] = 920.0
    K[:, 0, 2] = 512.0
    K[:, 1, 2] = 384.0
    K[:, 2, 2] = 1.0
    return K


def real_dist(B=1) -> torch.Tensor:
    """Mild KB distortion (k1..k4 ≈ small)."""
    return torch.tensor([[-0.05, 0.01, -0.002, 0.0005]], dtype=torch.float64).expand(B, 4).contiguous()


DOF_PRESETS = {
    '2dof':  ['omega_x', 'omega_y'],
    '6dof':  ['omega_x', 'omega_y', 'omega_z', 'tx', 'ty', 'tz'],
    '10dof': ['omega_x', 'omega_y', 'omega_z', 'tx', 'ty', 'tz',
              'dfx', 'dfy', 'dcx', 'dcy'],
}


def sample_delta_gt(dof_names, *, rot_deg=0.30, t_m=0.05, dfx_pct=0.01,
                    dcxy_px=2.0, seed=0) -> torch.Tensor:
    rng = np.random.RandomState(seed)
    out = []
    for nm in dof_names:
        if nm.startswith('omega'):
            out.append(rng.uniform(-rot_deg, rot_deg))
        elif nm in ('tx', 'ty', 'tz'):
            out.append(rng.uniform(-t_m, t_m))
        elif nm in ('dfx', 'dfy'):
            out.append(rng.uniform(-dfx_pct, dfx_pct))
        elif nm in ('dcx', 'dcy'):
            out.append(rng.uniform(-dcxy_px, dcxy_px))
        else:
            raise KeyError(nm)
    return torch.tensor(out, dtype=torch.float64).unsqueeze(0)   # (1, K)


# ─── forward project under a δ (using shared apply_extrinsic + K_with_delta) ─

def project_with_delta(P0: torch.Tensor, K: torch.Tensor, dist: torch.Tensor | None,
                        delta: torch.Tensor, dof_names) -> torch.Tensor:
    """Apply δ to truth (P0, K) and project. (B, N, 3) + (B, K)
    → (B, N, 2). dist=None → pinhole, else KB."""
    B = P0.shape[0]
    z_dummy = torch.zeros(B, dtype=P0.dtype, device=P0.device)

    def _g(name):
        if name in dof_names:
            return delta[..., dof_names.index(name)]
        return z_dummy
    omega = torch.stack([_g('omega_x'), _g('omega_y'), _g('omega_z')], dim=-1)
    t_v = torch.stack([_g('tx'), _g('ty'), _g('tz')], dim=-1)
    K_pert = _K_with_delta(K, _g('dfx'), _g('dfy'), _g('dcx'), _g('dcy'))
    P_pert = _apply_extrinsic(P0, omega, t_v)
    if dist is None:
        return project_pinhole(P_pert, K_pert)
    else:
        return project_kb(P_pert, K_pert, dist)


# ─── (A) pose roundtrip ───────────────────────────────────────────────

def test_pose_roundtrip(dof_names, *, model='pinhole', n_pts=200,
                        rot_deg=0.30, t_m=0.05, dfx_pct=0.01, dcxy_px=2.0,
                        max_iter=20, tol=1e-10, seed=1):
    """Run one trial of pose roundtrip; return (n_iter, final_err)."""
    P0 = make_cam_xyz(n_pts, seed=seed).unsqueeze(0)        # (1, N, 3)
    K = real_K(1)
    dist = real_dist(1) if model == 'kb' else None

    delta_gt = sample_delta_gt(dof_names, rot_deg=rot_deg, t_m=t_m,
                                dfx_pct=dfx_pct, dcxy_px=dcxy_px, seed=seed)

    # Forward: truth pose vs perturbed pose
    if model == 'pinhole':
        uv_truth = project_pinhole(P0, K)
    else:
        uv_truth = project_kb(P0, K, dist)
    uv_pert = project_with_delta(P0, K, dist, delta_gt, dof_names)
    duv = uv_pert - uv_truth
    z = P0[..., 2].clone()
    valid = torch.ones(P0.shape[:2], dtype=torch.bool)
    W = torch.eye(2, dtype=torch.float64).expand(1, n_pts, 2, 2).contiguous()

    # Iterate the solver, tracking convergence
    errs = []
    for n_iter in range(1, max_iter + 1):
        if model == 'pinhole':
            delta_est, _ = solve_pinhole(uv_truth, duv, W, z, K, dof_names,
                                          valid=valid, n_iter=n_iter, damping=0.0)
        else:
            delta_est, _ = solve_kb(uv_truth, duv, W, z, K, dist, dof_names,
                                     valid=valid, n_iter=n_iter, damping=0.0)
        err = (delta_est - delta_gt).abs().max().item()
        errs.append(err)
        if err < tol:
            return n_iter, err, errs
    return max_iter, errs[-1], errs


# ─── (B0) ANALYTIC covariance roundtrip ───────────────────────────────
#
#   Σ_δ_gt  →  Σ_uv,i = J_i Σ_δ_gt J_iᵀ  (per-point)
#   W_i = Σ_uv,i⁻¹
#   H   = Σ_i J_iᵀ W_i J_i
#   Σ_δ_est = H⁻¹
# In the linear regime (J fixed at truth), this MUST round-trip to machine
# precision irrespective of N as long as the per-point geometry is non-
# degenerate. ANY mismatch here = scale/sign bug somewhere in J.

def test_covariance_roundtrip_analytic(dof_names, *, model='pinhole',
                                        n_pts=1000, seed=3,
                                        sigma_omega=0.05, sigma_t=0.02,
                                        sigma_dfx=0.005, sigma_dcxy=1.0):
    rng = np.random.RandomState(seed)
    P0 = make_cam_xyz(n_pts, seed=seed).unsqueeze(0)
    K = real_K(1)
    dist = real_dist(1) if model == 'kb' else None

    K_dim = len(dof_names)

    # Build a physically-reasonable PSD Σ_δ_gt: per-axis std baked from
    # rough scale of each DoF, then mixed by random rotation so off-diag
    # is non-trivial.
    stds = []
    for nm in dof_names:
        if nm.startswith('omega'):
            stds.append(sigma_omega)
        elif nm in ('tx', 'ty', 'tz'):
            stds.append(sigma_t)
        elif nm in ('dfx', 'dfy'):
            stds.append(sigma_dfx)
        elif nm in ('dcx', 'dcy'):
            stds.append(sigma_dcxy)
        else:
            raise KeyError(nm)
    stds = np.array(stds, dtype=np.float64)
    # Random orthogonal Q via QR on a Gaussian
    A = rng.randn(K_dim, K_dim)
    Q, _ = np.linalg.qr(A)
    D = np.diag(stds ** 2)
    Sigma_gt_np = Q @ D @ Q.T
    Sigma_gt = torch.from_numpy(Sigma_gt_np)         # (K, K)

    # Compute J at truth
    if model == 'pinhole':
        uv_truth = project_pinhole(P0, K)
        Xc, Yc, Zc = P0.unbind(-1)
        J = pinhole_jacobian(Xc, Yc, Zc, K, uv_truth, dof_names)
    else:
        uv_truth = project_kb(P0, K, dist)
        Xc, Yc, Zc = P0.unbind(-1)
        J = kb_jacobian(Xc, Yc, Zc, K, dist, dof_names)
    # J: (1, N, 2, K)

    # Σ_uv,i = J_i Σ_gt J_iᵀ  → (1, N, 2, 2)
    Sigma_uv = torch.einsum('bnik,kl,bnjl->bnij', J, Sigma_gt, J)
    # add a TINY ridge so per-point Σ_uv is invertible even when J_i is
    # near-rank-1 (e.g. a single point can't see all 6 DoFs). The ridge
    # mimics observation noise; with ε small enough it doesn't affect the
    # roundtrip when summed over many points.
    eye2 = torch.eye(2, dtype=torch.float64).expand_as(Sigma_uv)
    ridge_pix2 = 1e-8
    W = torch.linalg.inv(Sigma_uv + ridge_pix2 * eye2)
    H = torch.einsum('bnik,bnij,bnjl->bkl', J, W, J)[0]
    Sigma_est = torch.linalg.inv(H)

    err_abs = (Sigma_est - Sigma_gt).abs().max().item()
    rel = (Sigma_est - Sigma_gt).abs() / Sigma_gt.abs().clamp_min(1e-30)
    err_rel = rel.max().item()
    return Sigma_gt, Sigma_est, err_abs, err_rel


# ─── (B) MC covariance roundtrip (legacy) ─────────────────────────────

def test_covariance_roundtrip(dof_names, *, model='pinhole', n_pts=200,
                              n_trials=2000, sigma_pix=1.0, seed=2,
                              gn_iter=4):
    """Monte-Carlo: with σ_pix=1px Gaussian observation noise on uv,
    does empirical Cov(δ̂ - δ_gt) match H⁻¹ from the GN solve?

    True δ_gt is fixed at 0 (we measure noise variance around it). The
    estimator is unbiased for small noise so Cov(δ̂) ≈ H⁻¹.
    """
    rng = np.random.RandomState(seed)
    P0 = make_cam_xyz(n_pts, seed=seed).unsqueeze(0)        # (1, N, 3)
    K = real_K(1)
    dist = real_dist(1) if model == 'kb' else None

    if model == 'pinhole':
        uv_truth = project_pinhole(P0, K)
    else:
        uv_truth = project_kb(P0, K, dist)
    z = P0[..., 2].clone()
    valid = torch.ones(P0.shape[:2], dtype=torch.bool)

    # W = (1/σ_pix²) I
    W = torch.eye(2, dtype=torch.float64).expand(1, n_pts, 2, 2).contiguous()
    W = W / (sigma_pix ** 2)

    # Run one solve at δ=0 to grab H (analytic Cramér-Rao bound)
    K_dim = len(dof_names)
    if model == 'pinhole':
        # Build J at truth, compute H by hand at δ=0
        Xc, Yc, Zc = P0.unbind(-1)
        J = pinhole_jacobian(Xc, Yc, Zc, K, uv_truth, dof_names)  # (1,N,2,K)
    else:
        Xc, Yc, Zc = P0.unbind(-1)
        J = kb_jacobian(Xc, Yc, Zc, K, dist, dof_names)
    H_analytic = torch.einsum('bnik,bnij,bnjl->bkl', J, W, J)[0]  # (K, K)
    Sigma_analytic = torch.linalg.inv(H_analytic)                  # (K, K)

    # Monte Carlo
    deltas = torch.zeros(n_trials, K_dim, dtype=torch.float64)
    for t in range(n_trials):
        noise = torch.tensor(
            rng.randn(1, n_pts, 2) * sigma_pix, dtype=torch.float64,
        )
        duv = noise   # δ_gt = 0, so target = uv_truth + noise
        if model == 'pinhole':
            de, _ = solve_pinhole(uv_truth, duv, W, z, K, dof_names,
                                   valid=valid, n_iter=gn_iter, damping=0.0)
        else:
            de, _ = solve_kb(uv_truth, duv, W, z, K, dist, dof_names,
                              valid=valid, n_iter=gn_iter, damping=0.0)
        deltas[t] = de[0]

    Sigma_mc = torch.from_numpy(np.cov(deltas.numpy().T))   # (K, K)

    return Sigma_analytic, Sigma_mc


# ─── reporting helpers ────────────────────────────────────────────────

def fmt_per_axis(diag, dof_names):
    return '  '.join(f'{nm}={v:.3e}' for nm, v in zip(dof_names, diag))


def main():
    print('=' * 78)
    print('  (A) POSE ROUNDTRIP — # iterations to ‖δ_est − δ_gt‖∞ < 1e-10')
    print('=' * 78)
    for model in ('pinhole', 'kb'):
        for preset, dof_names in DOF_PRESETS.items():
            results = []
            for seed in range(5):
                n_iter, err, errs = test_pose_roundtrip(
                    dof_names, model=model, seed=seed)
                results.append((n_iter, err, errs))
            n_iters = [r[0] for r in results]
            errs = [r[1] for r in results]
            best_traj = results[0][2]
            print(f'  [{model:7s} {preset:5s}]  n_iter ∈ {min(n_iters)}-{max(n_iters)}'
                  f'  final_err {min(errs):.2e}-{max(errs):.2e}')
            traj_str = ', '.join(f'{e:.1e}' for e in best_traj[:8])
            print(f'              seed=0 traj: {traj_str}')
    print()

    print('=' * 78)
    print('  (B0) ANALYTIC COVARIANCE ROUNDTRIP')
    print('     Σ_δ_gt → Σ_uv = J Σ J^T → W = Σ_uv⁻¹ → H = Σ JᵀWJ → Σ_δ_est')
    print('     N=1000 pts, ridge=1e-8 px². Should hit machine precision in')
    print('     the linear regime if J has consistent units.')
    print('=' * 78)
    for model in ('pinhole', 'kb'):
        for preset, dof_names in DOF_PRESETS.items():
            Sgt, Sest, eabs, erel = test_covariance_roundtrip_analytic(
                dof_names, model=model, n_pts=1000, seed=3)
            std_gt = Sgt.diag().sqrt().numpy()
            std_es = Sest.diag().sqrt().numpy()
            ratio = std_es / std_gt.clip(min=1e-30)
            print(f'  [{model:7s} {preset:5s}]  max |ΔΣ|={eabs:.2e}  '
                  f'max rel={erel:.2e}')
            print(f'    σ_gt  : {fmt_per_axis(std_gt, dof_names)}')
            print(f'    σ_est : {fmt_per_axis(std_es, dof_names)}')
            print(f'    ratio : {fmt_per_axis(ratio, dof_names)}')
            print()

    print('=' * 78)
    print('  (B) MC COVARIANCE — empirical Cov(δ̂) vs H⁻¹ (Cramér-Rao)')
    print('     σ_pix=1.0,  n_trials=2000,  n_pts=200')
    print('=' * 78)
    for model in ('pinhole', 'kb'):
        for preset, dof_names in DOF_PRESETS.items():
            Sigma_a, Sigma_mc = test_covariance_roundtrip(
                dof_names, model=model, n_trials=2000, sigma_pix=1.0,
                gn_iter=4, seed=10)
            diag_a = Sigma_a.diag().sqrt().numpy()
            diag_mc = Sigma_mc.diag().sqrt().numpy()
            ratio = diag_mc / diag_a.clip(min=1e-30)
            print(f'  [{model:7s} {preset:5s}]')
            print(f'    σ_analytic (sqrt diag): {fmt_per_axis(diag_a, dof_names)}')
            print(f'    σ_empirical          :  {fmt_per_axis(diag_mc, dof_names)}')
            print(f'    ratio (mc/analytic)  :  {fmt_per_axis(ratio, dof_names)}')
            # Also report off-diagonal correlation match
            corr_a = Sigma_a / (Sigma_a.diag().sqrt().unsqueeze(0)
                                 * Sigma_a.diag().sqrt().unsqueeze(1)).clamp_min(1e-30)
            corr_mc = Sigma_mc / (Sigma_mc.diag().sqrt().unsqueeze(0)
                                   * Sigma_mc.diag().sqrt().unsqueeze(1)).clamp_min(1e-30)
            corr_err = (corr_a - corr_mc).abs().max().item()
            print(f'    max |corr_a − corr_mc| (off-diag) = {corr_err:.2e}')
            print()


if __name__ == '__main__':
    main()
