"""Multi-frame BA with perturbed intrinsic: fx-scale AND KB-radial distortion.

Hypothesis test: if the BA solver's camera model is slightly wrong (wrong fx,
or missing KB distortion), does the shared multi-frame extrinsic still
recover the GT perturbation?

Setup (same as ba_multiframe):
  • Scene 015, N=10 consecutive val frames.
  • Sample ONE shared cam-frame rig drift (ypr_cam, t_cam).
  • For each frame run CalibNetDepth → per-point Gaussians (using TRUE K).
  • BA solves one 6-DoF θ shared across all frames, using a PERTURBED K model.
  • Vary perturbation: fx-scale δ, KB-radial k2.

Output: experiments/all_v3_mc/ba_kb/summary.json + hero.png
"""
import json, time
from collections import defaultdict
from pathlib import Path

import numpy as np
import torch
import pyceres
import matplotlib; matplotlib.use('Agg')
import matplotlib.pyplot as plt

from dataset_pandaset import PandaSetCalibDataset
from model_depth import CalibNetDepth
import ba_singleframe as bas
import ba_multiframe as bam

import os as _os
CACHE_PATH = '/mnt/nvme6t/e2e_calib_cache/pandaset_mc_cache.pt'
# override with BA_CKPT / BA_DEFORM_MODE / BA_OUT env vars for sanity-testing
# alternative checkpoints (e.g., deformable variants).
CKPT       = Path(_os.environ.get('BA_CKPT',   'experiments/all_v3_mc/best_model.pt'))
DEFORM_MODE = _os.environ.get('BA_DEFORM_MODE', 'none')
OUT_ROOT   = Path(_os.environ.get('BA_OUT',    'experiments/all_v3_mc/ba_kb'))
DEVICE     = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
bas.DEVICE = DEVICE
bam.DEVICE = DEVICE
SCENE      = '015'
N_FRAMES   = 10
SIGMA_YPR  = 0.5
SIGMA_TR   = 0.20
N_ITERS    = 3
SEED       = 42


# ── KB radial distortion ─────────────────────────────────────────────────────
def apply_kb(uv, K, k):
    """Forward KB distortion: straight r → distorted r*(1 + k2 r^2 + k4 r^4).
    uv: (N, 2) in pixels.  K: (3,3).  k: (k2, k4) or None.
    Returns distorted uv in pixels.
    """
    if k is None or (k[0] == 0 and k[1] == 0):
        return uv
    fx, fy, cx, cy = K[0,0], K[1,1], K[0,2], K[1,2]
    x = (uv[..., 0] - cx) / fx
    y = (uv[..., 1] - cy) / fy
    r2 = x*x + y*y
    f = 1 + k[0]*r2 + k[1]*r2*r2
    return np.stack([fx * x * f + cx, fy * y * f + cy], axis=-1)


# ── cost that uses a perturbed K model ───────────────────────────────────────
class CalibBACostPerturbed(pyceres.CostFunction):
    """Same residuals as bas.CalibBACost but projects through (K_ba, kb_ba).

      residual = sqrt_info @ (KB(π_Kba(R(ypr) P + t)) - (uv_ref + d))

    uv_ref and d were generated by the pipeline using TRUE K; BA's projection
    uses the WRONG (K_ba, kb_ba) — this simulates a solver that doesn't know
    the true intrinsic.
    """
    def __init__(self, P, uv_ref, d, sqrt_info, K_ba, kb_ba=None):
        super().__init__()
        self.P, self.uv_ref, self.d, self.L = P, uv_ref, d, sqrt_info
        self.K_ba = K_ba
        self.kb_ba = kb_ba
        self.fx, self.fy = K_ba[0,0], K_ba[1,1]
        self.cx, self.cy = K_ba[0,2], K_ba[1,2]
        self.N = P.shape[0]
        self.set_num_residuals(2 * self.N)
        self.set_parameter_block_sizes([6])

    def _residuals(self, θ):
        R = bas.ypr_to_R(θ[:3])
        t = θ[3:6]
        Q = self.P @ R.T + t
        proj = np.stack([self.fx * Q[:,0]/Q[:,2] + self.cx,
                         self.fy * Q[:,1]/Q[:,2] + self.cy], axis=1)
        if self.kb_ba is not None:
            proj = apply_kb(proj, self.K_ba, self.kb_ba)
        r_raw = proj - self.uv_ref - self.d
        return np.einsum('nij,nj->ni', self.L, r_raw).ravel()

    def Evaluate(self, params, residuals, jacobians):
        θ = np.asarray(params[0]).copy()
        residuals[:] = self._residuals(θ)
        if jacobians is not None and jacobians[0] is not None:
            eps = 1e-5
            J = np.zeros((2*self.N, 6))
            for k in range(6):
                tp = θ.copy(); tp[k] += eps
                tm = θ.copy(); tm[k] -= eps
                J[:, k] = (self._residuals(tp) - self._residuals(tm)) / (2*eps)
            jacobians[0][:] = J.ravel()
        return True


def solve_multi_perturbed(all_obs, K_ba, kb_ba):
    """all_obs: list of (P_cam, uv_ref, d_shift, Sigma, K_true)."""
    theta = np.zeros(6)
    prob = pyceres.Problem()
    for P, ur, d, Σ, K_true in all_obs:
        N = P.shape[0]
        L = np.zeros_like(Σ)
        for i in range(N):
            try:
                L[i] = np.linalg.cholesky(np.linalg.inv(Σ[i])).T
            except np.linalg.LinAlgError:
                L[i] = np.eye(2)
        prob.add_residual_block(
            CalibBACostPerturbed(P, ur, d, L, K_ba, kb_ba), None, [theta])
    opts = pyceres.SolverOptions()
    opts.linear_solver_type = pyceres.LinearSolverType.DENSE_QR
    opts.max_num_iterations = 50
    opts.minimizer_progress_to_stdout = False
    summ = pyceres.SolverSummary()
    pyceres.solve(opts, prob, summ)
    return theta, summ


def iterate_multi_perturbed(model, frames, ypr_gt_cam, t_gt_cam,
                             fx_scale=1.0, kb_ba=None, n_iters=N_ITERS):
    """Like bam.iterate_multi but BA uses a perturbed K."""
    ypr_est_cam = np.zeros(3)
    t_est_cam   = np.zeros(3)
    history = []
    for it in range(n_iters):
        ypr_res = ypr_gt_cam - ypr_est_cam
        t_res   = t_gt_cam   - t_est_cam

        all_obs = []
        total_pts = 0
        for fp in frames:
            obs = bam.frame_observations(model, fp['instances'], fp['inst_idxs'],
                                          ypr_res, t_res, fp['R_gt_c2w'], fp['K'])
            if obs is None:
                continue
            P, ur, d, Σ, K_true, _ = obs
            # build perturbed K for BA
            K_ba = K_true.copy()
            K_ba[0,0] *= fx_scale
            K_ba[1,1] *= fx_scale
            all_obs.append((P, ur, d, Σ, K_ba))
            total_pts += P.shape[0]
        if total_pts < 40:
            break
        # pass through a dummy K_ba (all identical — per-frame K already embedded)
        θ, summ = solve_multi_perturbed(all_obs, all_obs[0][4], kb_ba)
        Δypr = θ[:3]; Δt = θ[3:6]
        ypr_est_cam = ypr_est_cam + Δypr
        t_est_cam   = t_est_cam   + Δt
        history.append(dict(iter=it, n_pts=total_pts,
                             dypr=Δypr.round(4).tolist(),
                             dt_cm=(Δt*100).round(3).tolist(),
                             initial_cost=float(summ.initial_cost),
                             final_cost=float(summ.final_cost)))
        if np.linalg.norm(Δypr) < 1e-3 and np.linalg.norm(Δt) < 1e-4:
            break
    return ypr_est_cam, t_est_cam, history


def main():
    print('[1] loading dataset & model')
    ds = PandaSetCalibDataset(CACHE_PATH, split='val')
    model = CalibNetDepth(img_size=64, in_channels=3, n_layers=4,
                           use_convnext=True, use_frustum=True,
                           deform_mode=DEFORM_MODE).to(DEVICE)
    model.load_state_dict(torch.load(CKPT, map_location=DEVICE, weights_only=True))
    model.eval()

    print(f'[2] discovering frames in scene {SCENE}')
    found = bam.discover_frames(ds.instances, SCENE, N_FRAMES)
    print(f'  {len(found)} frames: fi={[f[0] for f in found]}')
    frames = []
    for fi, key, inst_idxs in found:
        first = ds.instances[inst_idxs[0]]
        frames.append(dict(
            fi=fi, key=key, inst_idxs=inst_idxs, instances=ds.instances,
            first=first,
            K        = first['K_full'].numpy(),
            R_gt_c2w = first['R_gt'].numpy(),
            cp       = first['cam_pos'].numpy(),
        ))

    rng = np.random.default_rng(SEED)
    ypr_gt_cam = (rng.random(3)*2 - 1) * SIGMA_YPR
    t_gt_cam   = (rng.random(3)*2 - 1) * SIGMA_TR
    print(f'[3] shared GT cam-frame drift:')
    print(f'    ypr_cam = {ypr_gt_cam.round(3)}°  ||={np.linalg.norm(ypr_gt_cam):.3f}°')
    print(f'    t_cam   = {(t_gt_cam*100).round(2)}cm ||={np.linalg.norm(t_gt_cam)*100:.2f}cm')

    # sweep intrinsic perturbations
    # 1. fx scale: 1.0 (baseline), 0.995, 0.99, 0.98, 0.97, 1.01, 1.02
    # 2. KB k2: 0, 0.01, 0.05, 0.1, -0.05, -0.1  (pincushion/barrel)
    EXPERIMENTS = [
        ('pinhole_ref',      dict(fx_scale=1.000, kb_ba=None)),
        ('fx_-0.5pct',        dict(fx_scale=0.995, kb_ba=None)),
        ('fx_-1.0pct',        dict(fx_scale=0.990, kb_ba=None)),
        ('fx_-2.0pct',        dict(fx_scale=0.980, kb_ba=None)),
        ('fx_-5.0pct',        dict(fx_scale=0.950, kb_ba=None)),
        ('fx_+1.0pct',        dict(fx_scale=1.010, kb_ba=None)),
        ('fx_+2.0pct',        dict(fx_scale=1.020, kb_ba=None)),
        ('kb_k2=+0.01',       dict(fx_scale=1.000, kb_ba=(0.01, 0.0))),
        ('kb_k2=+0.05',       dict(fx_scale=1.000, kb_ba=(0.05, 0.0))),
        ('kb_k2=+0.10',       dict(fx_scale=1.000, kb_ba=(0.10, 0.0))),
        ('kb_k2=-0.05',       dict(fx_scale=1.000, kb_ba=(-0.05, 0.0))),
        ('kb_k2=-0.10',       dict(fx_scale=1.000, kb_ba=(-0.10, 0.0))),
    ]

    results = []
    for name, kw in EXPERIMENTS:
        t0 = time.time()
        ypr_m, t_m_cam, hist = iterate_multi_perturbed(
            model, frames, ypr_gt_cam, t_gt_cam, **kw)
        dt = time.time() - t0
        rot_err = float(np.rad2deg(np.arccos(np.clip(
            (np.trace(bas.ypr_to_R(ypr_m).T @ bas.ypr_to_R(ypr_gt_cam)) - 1) / 2, -1, 1))))
        t_err_cm = float(np.linalg.norm(t_m_cam - t_gt_cam) * 100)

        reprojs = []
        for fp in frames:
            after = bam.reproj_err_px(fp, ypr_gt_cam - ypr_m, t_gt_cam - t_m_cam)
            reprojs.append(after)
        before = bam.reproj_err_px(frames[0], ypr_gt_cam, t_gt_cam)

        print(f'  {name:16s} fx={kw["fx_scale"]:.3f}  kb={kw["kb_ba"]}  '
              f'→ rot_err={rot_err:.3f}°  t_err={t_err_cm:.2f}cm  '
              f'reproj med={np.median(reprojs):.2f}  ({dt:.0f}s)')

        results.append(dict(
            name=name,
            fx_scale=kw['fx_scale'],
            kb_ba=kw['kb_ba'],
            ypr_est_deg=ypr_m.tolist(),
            t_est_cm=(t_m_cam*100).tolist(),
            rot_err_deg=rot_err,
            t_err_cm=t_err_cm,
            reproj_before_px=float(before),
            reproj_after_med_px=float(np.median(reprojs)),
            reproj_after_max_px=float(max(reprojs)),
            iters=len(hist),
            wall_s=dt,
        ))

    OUT_ROOT.mkdir(parents=True, exist_ok=True)
    summary = dict(
        scene=SCENE, n_frames=len(frames),
        ypr_gt_cam_deg=ypr_gt_cam.tolist(),
        t_gt_cam_cm=(t_gt_cam*100).tolist(),
        sigma_ypr_deg=SIGMA_YPR, sigma_t_m=SIGMA_TR,
        results=results,
    )
    (OUT_ROOT / 'summary.json').write_text(json.dumps(summary, indent=2))
    print(f'\nsaved → {OUT_ROOT}/summary.json')

    # ── plot: rot_err & t_err vs perturbation magnitude ──────────────────────
    fig, axes = plt.subplots(1, 2, figsize=(14, 5), dpi=130)
    fig.patch.set_facecolor('#f6f4ed')
    for ax in axes:
        ax.set_facecolor('#fff')
        for sp in ('top','right'): ax.spines[sp].set_visible(False)
        ax.grid(alpha=0.25)

    fx_entries = [r for r in results if r['kb_ba'] is None]
    kb_entries = [r for r in results if r['kb_ba'] is not None]

    ax = axes[0]
    fx_pcts = [(r['fx_scale'] - 1.0) * 100 for r in fx_entries]
    ax.plot(fx_pcts, [r['rot_err_deg'] for r in fx_entries], 'o-',
             color='#174734', label='rot err (deg)', lw=2, ms=7)
    ax.set_xlabel('fx perturbation (%)', fontsize=10)
    ax.set_ylabel('rot err (deg)', color='#174734', fontsize=10)
    ax.tick_params(axis='y', labelcolor='#174734')
    ax2 = ax.twinx()
    ax2.plot(fx_pcts, [r['t_err_cm'] for r in fx_entries], 's-',
              color='#c13c14', label='t err (cm)', lw=2, ms=7)
    ax2.set_ylabel('t err (cm)', color='#c13c14', fontsize=10)
    ax2.tick_params(axis='y', labelcolor='#c13c14')
    ax.set_title(f'BA recovery vs fx mis-match\n'
                  f'(GT pert: ypr ||={np.linalg.norm(ypr_gt_cam):.2f}°, '
                  f't ||={np.linalg.norm(t_gt_cam)*100:.1f}cm)',
                  fontsize=10, loc='left')
    ax.axvline(0, color='k', lw=0.5, alpha=0.3)

    ax = axes[1]
    kb_vals = [r['kb_ba'][0] for r in kb_entries]
    ax.plot(kb_vals, [r['rot_err_deg'] for r in kb_entries], 'o-',
             color='#174734', label='rot err (deg)', lw=2, ms=7)
    ax.set_xlabel('KB k₂', fontsize=10)
    ax.set_ylabel('rot err (deg)', color='#174734', fontsize=10)
    ax.tick_params(axis='y', labelcolor='#174734')
    ax2 = ax.twinx()
    ax2.plot(kb_vals, [r['t_err_cm'] for r in kb_entries], 's-',
              color='#c13c14', label='t err (cm)', lw=2, ms=7)
    ax2.set_ylabel('t err (cm)', color='#c13c14', fontsize=10)
    ax2.tick_params(axis='y', labelcolor='#c13c14')
    ax.set_title('BA recovery vs KB k₂ (radial distortion)\n'
                 '(k₂>0 pincushion, k₂<0 barrel)', fontsize=10, loc='left')
    ax.axvline(0, color='k', lw=0.5, alpha=0.3)

    plt.tight_layout()
    plt.savefig(OUT_ROOT / 'summary.png', dpi=130, bbox_inches='tight',
                facecolor='#f6f4ed')
    plt.close(fig)
    print(f'saved → {OUT_ROOT}/summary.png')


if __name__ == '__main__':
    main()
