# Image to run gsplat 1.5.3 examples/simple_trainer.py
FROM e2e-calib-splatkb:v0

ENV DEBIAN_FRONTEND=noninteractive
RUN pip install --no-cache-dir \
        "git+https://github.com/rmbrualla/pycolmap@cc7ea4b7301720ac29287dbe450952511b32125e" \
        "git+https://github.com/nerfstudio-project/nerfview@4538024fe0d15fd1a0e4d760f3695fc44ca72787" \
        "viser" \
        "imageio[ffmpeg]" \
        "numpy<2.0.0" \
        "scikit-learn" \
        "tqdm" \
        "torchmetrics[image]" \
        "tyro>=0.8.8" \
        "Pillow" \
        "tensorboard" \
        "tensorly" \
        "pyyaml" \
        "matplotlib" \
        "plyfile" \
        "splines"

WORKDIR /workspace
