#!/bin/bash
# Train→build→test release pipeline for CalibNet2 kmwv_calok.
#
# Call after training finishes:
#   EXP=experiments/kmwv_calok_s3_ba40_1003_1107 scripts/release_kmwv.sh
#
# Steps:
#   1. force-add best_model.pt + config.py + train.log to git
#   2. patch infra/Dockerfile.serve + entrypoint.serve.sh to the new exp
#   3. docker build -f infra/Dockerfile.serve -t e2e-calib-serve:gpu
#   4. docker run healthcheck + smoke POST /calibrate/generic/frame
#   5. tag_model.py → ClearML Model Registry (latest + prod)
#   6. git commit + push
#
# Any step that fails aborts the pipeline; nothing is pushed partially.
set -euo pipefail

: "${EXP:?EXP=experiments/<name> required}"
EXP_NAME=$(basename "$EXP")
REPO=/home/hfunaya/git/e2e_calib
cd "$REPO"

echo "[release] exp=$EXP_NAME"

# 1. Reconstitute best_model.pt from last_model.pt if missing (ClearML
#    update_weights can consume the file). sha should match the one logged.
if [ ! -f "$EXP/best_model.pt" ] && [ -f "$EXP/last_model.pt" ]; then
    echo "[release] best_model.pt missing, copying from last_model.pt (ep50 identity)"
    docker run --rm -v "$REPO:/workspace" -w /workspace e2e-calib-train:np2 \
        bash -c "cp $EXP/last_model.pt $EXP/best_model.pt && chown -R $(id -u):$(id -g) $EXP"
fi
[ -f "$EXP/best_model.pt" ] || { echo "[release] ERROR: no best_model.pt in $EXP"; exit 1; }

# 2. Force-add + patch infra/
git add -f "$EXP/best_model.pt" "$EXP/config.py" "$EXP/train.log"
sed -i -E "s|/app/weights/[^/ ]+|/app/weights/$EXP_NAME|g" infra/entrypoint.serve.sh
sed -i -E "s|experiments/[^/]+/(best_model\.pt|config\.py)|experiments/$EXP_NAME/\1|g" infra/Dockerfile.serve
git add infra/Dockerfile.serve infra/entrypoint.serve.sh

# 3. Build serving image
echo "[release] docker build e2e-calib-serve:gpu"
docker build -f infra/Dockerfile.serve -t e2e-calib-serve:gpu . 2>&1 | tail -8

# 4. Smoke: start container, GET /health, POST /calibrate/generic/frame with
#    a tiny canned payload, kill container.
echo "[release] smoke test"
docker run -d --name _release_smoke --gpus '"device=12"' -p 18501:8501 \
    e2e-calib-serve:gpu
sleep 15
for i in {1..20}; do
    if curl -sf http://localhost:18501/health >/dev/null; then break; fi
    sleep 2
done
curl -sf http://localhost:18501/health | python3 -m json.tool
curl -s http://localhost:18501/api/model_status 2>&1 | python3 -m json.tool 2>&1 | head -5 || true
docker stop _release_smoke >/dev/null; docker rm _release_smoke >/dev/null

# 5. ClearML tag release
echo "[release] clearml tag"
docker run --rm --network host \
    -v "$REPO:/workspace" -v /raid:/raid -v /mnt/fsx:/mnt/fsx \
    -v /mnt/fsx/.clearml_agent.dgx2-gpu.cfg:/root/clearml.conf:ro \
    --ipc=host -e PYTHONPATH=/workspace -w /workspace \
    e2e-calib-train:np2 \
    python3 -m scripts.serving.tag_model \
        --ckpt "$EXP/best_model.pt" \
        --name calib_best --project e2e_calib/calib \
        --tag latest --tag prod --demote calib_best \
        --comment "Auto-release of $EXP_NAME via scripts/release_kmwv.sh"

# 6. Git commit + push
git commit -m "Release $EXP_NAME

Auto-generated by scripts/release_kmwv.sh (train→build→test→tag).

Co-Authored-By: Claude Opus 4.7 <noreply@anthropic.com>" 2>&1 | tail -3
git push 2>&1 | tail -2
git push enterprise 2>&1 | tail -2
echo "[release] done"
